[Details]
  Icon = "../../theme/icons/fyne.png"
  Name = "chatGopher"
  ID = "github.albertchamberlain.chatGopher"
  Version = "2.3.0"
  Build = 10

[Development]
  HelperText = "This binary was build with debug symbol"

[Release]
  HelperText = "This binary was build without debug symbol"
